name: Generate animation SVG

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

jobs:
  generate_animation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate animation.svg
        run: |
          echo '<svg width="600" height="100" xmlns="http://www.w3.org/2000/svg">
                <rect width="100%" height="100%" fill="#20232a"/>
                <circle cx="50" cy="50" r="20" fill="#61dafb">
                  <animate attributeName="cx" from="50" to="550" dur="5s" repeatCount="indefinite" />
                </circle>
                <circle cx="50" cy="50" r="20" fill="#61dafb" opacity="0.5">
                  <animate attributeName="cx" from="50" to="550" dur="5s" begin="2.5s" repeatCount="indefinite" />
                </circle>
              </svg>' > animation.svg

      - name: Push animation.svg to repository
        uses: actions/upload-artifact@v2
        with:
          name: animation-svg
          path: animation.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
